@Harmonium_HostAddress = https://localhost:44372

GET {{Harmonium_HostAddress}}/api/utilisateur

###

POST {{Harmonium_HostAddress}}/api/utilisateur
Content-Type: application/json

{
  "id_vCode": 0,
  "uNom": "string",
  "uPrenom": "string",
  "email": "sathieughfghkfgh@hotmail.com",
  "uIdentifiant": "string",
  "uMotDePasse": "string",
  "adresse1": "string"
}
###

GET {{Harmonium_HostAddress}}/api/utilisateur/1

###

DELETE {{Harmonium_HostAddress}}/api/utilisateur/7

###

PUT {{Harmonium_HostAddress}}/api/utilisateur/6
Content-Type: application/json

{
  "id_Utilisateur": 6,
  "id_vCode": 2,
  "uNom": "",
  "uPrenom": "Mathieu",
  "email": "sathieumoleri@hotmail.com",
  "uIdentifiant": "UnautreIdentifiant",
  "uMotDePasse": "UnautreMotDePasse",
  "adresse1": "UneAdresse"
}

###

POST {{Harmonium_HostAddress}}/api/utilisateur
Content-Type: application/json

{
  //Utilisateur
}

###

GET {{Harmonium_HostAddress}}/api/utilisateur

###
